#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend Stellacandy.tech
	bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 53206-web-01 100.25.145.212:80
        server 53206-web-02 18.210.33.8:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
